# Generated by Django 4.2.4 on 2023-10-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0011_alter_cohorte_ano_alter_cursante_ano_aprobado_and_more'),
        ('inscripcion', '0004_aspirante_ano_egreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.cargo'),
        ),
    ]
