# Generated by Django 4.2.4 on 2023-10-05 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0011_alter_cohorte_ano_alter_cursante_ano_aprobado_and_more'),
        ('inscripcion', '0005_aspirante_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='mail_abc',
            field=models.EmailField(max_length=254, null=True, verbose_name='Mail ABC'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='mail_privado',
            field=models.EmailField(max_length=254, null=True, verbose_name='Mail privado'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='situacion_revista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.situacionrevista'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='telefono',
            field=models.CharField(max_length=100, null=True, verbose_name='Telefono'),
        ),
    ]
