# Generated by Django 4.2.4 on 2023-10-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0006_aspirante_direccion_aspirante_mail_abc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aspirante',
        ),
    ]
