# Generated by Django 4.0.5 on 2022-10-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_cargo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
            },
        ),
        migrations.CreateModel(
            name='Formador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Formador',
                'verbose_name_plural': 'Formadores',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_educativo', models.CharField(max_length=100)),
                ('cue', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='SituacionRevista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacion_revista', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Situación Revista',
                'verbose_name_plural': 'Situaciones Revista',
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Curso',
                'verbose_name_plural': 'Tipos de Curso',
            },
        ),
        migrations.CreateModel(
            name='TituloHabilitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nivel_titulo', models.CharField(max_length=100, verbose_name='Nivel del titulo')),
            ],
            options={
                'verbose_name': 'Título habilitante',
                'verbose_name_plural': 'Títulos habilitantes',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cursos_febrero', models.CharField(max_length=100)),
                ('mapda', models.CharField(max_length=100)),
                ('titulo_dispositivo', models.CharField(max_length=100)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.area')),
                ('cohorte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.cohorte')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.modalidad')),
                ('nombre_formador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.formador')),
                ('tipo_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.tipocurso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Cursante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('año_egreso', models.DateField(verbose_name='Año de egreso')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('mail_privado', models.EmailField(max_length=254, verbose_name='Mail privado')),
                ('mail_abc', models.EmailField(max_length=254, verbose_name='Mail ABC')),
                ('titulo_curso_aprobado', models.CharField(max_length=100, verbose_name='Titulos de cursos aprobados')),
                ('año_aprobado', models.DateField(verbose_name='REVISAR AÑO APROBADO')),
                ('area_aprobado', models.CharField(max_length=100, verbose_name='REVISAR AREA APROBADO')),
                ('cohorte_aprobado', models.DateField(verbose_name='REVISAR COHORTE APROBADO')),
                ('formador_aprobado', models.CharField(max_length=100, verbose_name='REVISAR FORMADOR APROBADO')),
                ('retiro_certificado', models.CharField(max_length=100, verbose_name='Forma del retiro del certificado')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.cargo')),
                ('cue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_cue', to='cursantes.institucion', verbose_name='CUE')),
                ('emisor_titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.institucion')),
                ('situacion_revista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.situacionrevista')),
                ('titulo_habilitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.titulohabilitante')),
            ],
            options={
                'verbose_name': 'Cursante',
                'verbose_name_plural': 'Cursantes',
            },
        ),
    ]
