# Generated by Django 4.0.5 on 2022-10-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursante',
            name='cohorte_aprobado',
            field=models.CharField(max_length=100, verbose_name='REVISAR COHORTE APROBADO'),
        ),
    ]
