# Generated by Django 4.0.5 on 2022-11-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0005_niveleducativo_servicios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='cursos_febrero',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='mapda',
        ),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria',
            field=models.CharField(default=0, max_length=100, verbose_name='Carga horaria'),
        ),
    ]
