# Generated by Django 4.0.5 on 2022-11-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0007_remove_cargo_nivel_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='nivel_educativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cursantes.niveleducativo'),
        ),
    ]
