# Generated by Django 4.0.5 on 2022-11-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0008_alter_institucion_nivel_educativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodispositivo',
            name='cantidad_horas',
            field=models.CharField(default=0, max_length=100, verbose_name='Cantidad horas'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='dictamen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='proyecto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='puntaje',
            field=models.CharField(default=0, max_length=100, verbose_name='Puntaje'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='resolucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
 
 