# Generated by Django 4.2.4 on 2023-10-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0011_alter_cohorte_ano_alter_cursante_ano_aprobado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='legajo',
            field=models.CharField(max_length=20, null=True, verbose_name='Legajo'),
        ),
    ]
