# Generated by Django 4.2.4 on 2023-11-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0012_cursante_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='dni',
            field=models.IntegerField(default=12345678, max_length=8, verbose_name='D.N.I'),
        ),
    ]
