# Generated by Django 4.2.4 on 2023-11-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0013_cursante_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursante',
            name='dni',
            field=models.IntegerField(default=12345678, verbose_name='D.N.I'),
        ),
    ]
