# Generated by Django 4.2.5 on 2023-11-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0015_alter_cursante_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='titulos',
            field=models.FileField(default=1, upload_to='archivos/titulos/', verbose_name='Títulos'),
            preserve_default=False,
        ),
    ]
