# Generated by Django 4.2.4 on 2023-11-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0015_alter_cursante_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaCursante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_asistidos', models.PositiveIntegerField(default=0)),
                ('dias_no_asistidos', models.PositiveIntegerField(default=0)),
                ('cursante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursantes.cursante')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursantes.curso')),
            ],
            options={
                'unique_together': {('cursante', 'curso')},
            },
        ),
    ]
