# Generated by Django 4.2.4 on 2023-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0016_asistenciacursante'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='dias_totales_transcurridos',
            field=models.IntegerField(default=0, verbose_name='Días totales transcurridos'),
        ),
    ]
