# Generated by Django 4.2.4 on 2023-11-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0017_curso_dias_totales_transcurridos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciacursante',
            name='cursante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursantes.cursante', verbose_name='cursante'),
        ),
        migrations.AlterField(
            model_name='asistenciacursante',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursantes.curso', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='asistenciacursante',
            name='dias_asistidos',
            field=models.PositiveIntegerField(default=0, verbose_name='dias asistidos'),
        ),
        migrations.AlterField(
            model_name='asistenciacursante',
            name='dias_no_asistidos',
            field=models.PositiveIntegerField(default=0, verbose_name='dias no asistidos'),
        ),
    ]
