# Generated by Django 4.2.4 on 2023-11-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0018_alter_asistenciacursante_cursante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciacursante',
            name='dias_no_asistidos',
        ),
    ]
