# Generated by Django 4.2.4 on 2023-11-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0019_remove_asistenciacursante_dias_no_asistidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobadosCursante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.BooleanField(default=False, verbose_name='cursantes aprobados')),
                ('cursante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursantes.cursante', verbose_name='cursante')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursantes.curso', verbose_name='curso')),
            ],
            options={
                'unique_together': {('cursante', 'curso')},
            },
        ),
    ]
