# Generated by Django 4.2.4 on 2023-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0020_aprobadoscursante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobadoscursante',
            name='nota',
            field=models.BooleanField(default=False, verbose_name='notas'),
        ),
    ]
