# Generated by Django 4.2.4 on 2023-11-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0016_cursante_titulos'),
        ('cursantes', '0022_alter_aprobadoscursante_nota'),
    ]

    operations = [
    ]
