# Generated by Django 4.2.4 on 2023-11-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursantes', '0023_merge_20231128_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursante',
            name='titulos',
            field=models.FileField(upload_to='archivo/titulos_validados/', verbose_name='Título'),
        ),
    ]
