# Generated by Django 4.2.4 on 2023-11-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajo_digital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='dni',
            field=models.IntegerField(default=12345678, verbose_name='D.N.I'),
        ),
    ]
