# Generated by Django 4.2.4 on 2023-11-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajo_digital', '0002_aspirante_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='dni',
            field=models.IntegerField(verbose_name='D.N.I'),
        ),
    ]
